<?php

require_once 'include/DB_Functions.php';
$db = new DB_Functions();

// json response array
$response = array("error" => FALSE);

if (isset($_POST['name']) && isset($_POST['email']) && isset($_POST['password'])) {

    // receiving the post params
    $name = $_POST['name'];
    $email = $_POST['email'];
    $password = $_POST['password'];

    // check if user is already existed with the same email
    if ($db->isUserExisted($email)) {
        // user already existed
        $response["error"] = TRUE;
        $response["error_msg"] = "User already existed with " . $email;
        echo json_encode($response);
    } else {
        // create a new user
        $user = $db->storeUser($name, $email, $password);
        $idid=$user["id"];
        $namnam=$user["name"];
        $res=$db->set_activated($idid,$namnam,"No");
        $prog=$db->set_progress($idid,$namnam,0);
        if ($user) {
            // user stored successfully
            $to      = $user["email"]; // Send email to our user
            $subject = "Signup | Verification"; // Give the email a subject
            $message = '
Hey '.$namnam.' ,<br><br>
Thanks for Signing up to fill my slambook!<br>
Your account has been created, you can login with the Email after you have activated your account by pressing the url below.<br><br>

Please click this link to activate your account:<br>
http://slambook.yagneshlp.com/verify.php?email='.$user["email"].'&hash='.$user["hash"].' <br><br><br>


This is Email was generated by a Bot. So, Please do not reply to this Email.<br>
For any help/queries, contact help@slambook.yagneshlp.com .

'; // Our message above including the link

$headers = 'From:Yagnesh L P <noreply@slambook.yagneshlp.com>' . "\r\n"; // Set from headers
$headers .= 'Content-type: text/html; charset=utf-8' . "\r\n"; //setting html pformated
if(!mail($to, $subject, $message, $headers)) // Send our email
{
    $response["error"] = TRUE;
      $response["message"] = "Email not working...";
      echo json_encode($response);
}
else

        {    $response["error"] = FALSE;
            $response["id"] = $idid;
            $response["uid"] = $user["unique_id"];
            $response["user"]["name"] = $user["name"];
            $response["user"]["email"] = $user["email"];
            $response["user"]["created_at"] = $user["created_at"];
            $response["user"]["updated_at"] = $user["updated_at"];
            $response["message"] = "Account Created successfully! Check your Email for verification link \n Login after verifying the email";
            echo json_encode($response);}
        } else {
            // user failed to store
            $response["error"] = TRUE;
            $response["error_msg"] = "Unknown error occurred in registration!";
            echo json_encode($response);
        }
    }
} else {
    $response["error"] = TRUE;
    $response["error_msg"] = "Required parameters (name, email or password) is missing!";
    echo json_encode($response);
}
?>
